[project]
name = "reverse-sheet-sky-children-of-the-light-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloredlogs>=15.0.1",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "pygame>=2.6.1",
]
